config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root to: "posts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  def self.persistent(id, values = {})
    Rails.cache.write("title:#{id}", values["title"]) if values["title"]
    Rails.cache.write("body:#{id}", values["body"]) if values["body"]

    new(
      title: Rails.cache.read("title:#{id}"),
      body: Rails.cache.read("body:#{id}")
    )
  end

  def self.clear_cache(id)
    Rails.cache.delete("step:#{id}")
    Rails.cache.delete("title:#{id}")
    Rails.cache.delete("body:#{id}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post ||= Post.persistent(session.id)
    @step ||= Rails.cache.fetch("step:#{session.id}") { :title }
  end

  def create
    @post = Post.create(post_params)
    Post.clear_cache(session.id)

    redirect_to @post
  end

  def show
    @post = Post.find(params[:id])
  end

  protected

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reflex</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="turbolinks-cache-control" content="no-cache">
  </head>

  <body>
    <div class="application">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts</h1>

<% if @posts %>
  <ul>
    <% @posts.each do |post| %>
      <li>
        <%= link_to post.title, post %>
      </li>
    <% end %>
  </ul>
<% end %>

<p><%= link_to "New post", new_post_path %></p>

app/views/posts/new.html.erb
<h1>New post</h1>

<p>Post: <%= @post.to_json %></p>

<%= form_with(model: @post, class: "wizard", data: { controller: "wizard" }) do |f| %>
  <% if @step == :title %>
    <%= f.text_field :title, placeholder: "Title", data: { target: "wizard.title" } %>

    <button data-action="click->wizard#next">Next</button>
  <% end %>

  <% if @step == :body %>
    <%= f.text_area :body, placeholder: "Body", data: { target: "wizard.body" } %>

    <button data-action="click->wizard#previous">Previous</button>
    <button data-action="click->wizard#next">Next</button>
  <% end %>

  <% if @step == :submit %>

    <div class="wizard-preview">
      <h2><%= @post.title %></h2>
      <p><%= @post.body %></p>
    </div>

    <%= f.hidden_field :title %>
    <%= f.hidden_field :body %>

    <button data-action="click->wizard#previous">Previous</button>
    <%= f.button "Save" %>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p>
  <%= @post.body %>
</p>

<p><%= link_to "Back to index", posts_path %></p>